In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('clean_final_data.csv')
df.head()

,OrderID,CustomerID,OrderDate,ProductID,Quantity,Discount,PaymentMethod,Status,Age,City,SignupDate,CustomerSegment,ProductName,Category,UnitPrice,Sales,OrderValue
0,500001,103695,2025-08-28,2003,4.0,10.0,Gateway,Completed,36.0,Qom,2024-03-05,Regular,USB-C Cable,Accessories,9.0,32.0,32.0
1,500002,107935,2024-05-31,2014,1.0,10.0,Wallet,Completed,49.0,Kerman,2025-06-04,Regular,Backpack,Accessories,42.0,38.0,38.0
2,500003,105141,2025-08-10,2002,1.0,20.0,CardToCard,Completed,36.0,Tehran,2025-10-19,Regular,Mechanical Keyboard,Electronics,62.0,50.0,50.0
3,500004,108780,2024-10-11,2012,1.0,10.0,Gateway,Completed,45.0,Shiraz,2023-12-07,Regular,Office Chair,Home Office,180.0,162.0,162.0
4,500005,101187,2024-02-19,2008,2.0,0.0,Gateway,Completed,24.0,Karaj,2023-12-02,Regular,Phone Case,Accessories,14.0,28.0,28.0

In [4]:
df.shape

(49222, 17)

In [5]:
df.duplicated().sum()

np.int64(0)

In [6]:
df.isna().sum()

OrderID            0
CustomerID         0
OrderDate          0
ProductID          0
Quantity           0
Discount           0
PaymentMethod      0
Status             0
Age                0
City               0
SignupDate         0
CustomerSegment    0
ProductName        0
Category           0
UnitPrice          0
Sales              0
OrderValue         0
dtype: int64

In [7]:
df.describe()

,OrderID,CustomerID,ProductID,Quantity,Discount,Age,UnitPrice,Sales,OrderValue
count,49222.000000,49222.000000,49222.000000,49222.000000,49222.000000,49222.000000,49222.000000,49222.000000,49222.000000
mean,525007.608366,105002.304356,2009.460160,1.881923,7.485576,41.283369,40.286579,69.985576,69.985576
std,14435.345449,2888.912895,5.578603,1.079382,7.754378,13.681355,42.613062,94.483273,94.483273
min,500001.000000,100001.000000,2001.000000,-2.000000,0.000000,18.000000,7.000000,-170.000000,-170.000000
25%,512507.250000,102504.000000,2004.000000,1.000000,0.000000,29.000000,11.000000,17.000000,17.000000
50%,525016.500000,105005.000000,2008.000000,2.000000,5.000000,41.000000,28.000000,38.000000,38.000000
75%,537506.750000,107497.000000,2014.000000,2.000000,10.000000,53.000000,58.000000,84.000000,84.000000
max,550000.000000,110000.000000,2020.000000,5.000000,30.000000,65.000000,260.000000,1300.000000,1300.000000

In [8]:
df.dtypes

OrderID              int64
CustomerID           int64
OrderDate           object
ProductID            int64
Quantity           float64
Discount           float64
PaymentMethod       object
Status              object
Age                float64
City                object
SignupDate          object
CustomerSegment     object
ProductName         object
Category            object
UnitPrice          float64
Sales              float64
OrderValue         float64
dtype: object

In [11]:
df['OrderDate'] = pd.to_datetime(df['OrderDate'],errors='coerce')
df['SignupDate'] = pd.to_datetime(df['SignupDate'],errors='coerce')

In [12]:
df.dtypes

OrderID                     int64
CustomerID                  int64
OrderDate          datetime64[ns]
ProductID                   int64
Quantity                  float64
Discount                  float64
PaymentMethod              object
Status                     object
Age                       float64
City                       object
SignupDate         datetime64[ns]
CustomerSegment            object
ProductName                object
Category                   object
UnitPrice                 float64
Sales                     float64
OrderValue                float64
dtype: object