MARK KEITH PLAYLIST

In [ ]:
import pandas as pd
df = pd.read_csv('insurance.csv')
df.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [5]:
df.describe()

               age          bmi     children       charges
count  1338.000000  1338.000000  1338.000000   1338.000000
mean     39.207025    30.663397     1.094918  13270.422265
std      14.049960     6.098187     1.205493  12110.011237
min      18.000000    15.960000     0.000000   1121.873900
25%      27.000000    26.296250     0.000000   4740.287150
50%      39.000000    30.400000     1.000000   9382.033000
75%      51.000000    34.693750     2.000000  16639.912515
max      64.000000    53.130000     5.000000  63770.428010

In [6]:
df.shape

(1338, 7)

In [7]:
df.columns

Index(['age', 'sex', 'bmi', 'children', 'smoker', 'region', 'charges'], dtype='object')

In [13]:
print("COUNT : ")
print(f'age: {df.age.count()}')
print(f'bmi: {df.bmi.count()}')
print(f'children: {df.children.count()}')
print(f'sex: {df.sex.count()}')
print(f'smoker: {df.smoker.count()}')
print(f'region: {df.region.count()}')

COUNT :
age: 1338
bmi: 1338
children: 1338
sex: 1338
smoker: 1338
region: 1338

In [15]:
print("UNIQUE: ")
print(f'age: {df.age.nunique()}')
print(f'bmi: {df.bmi.nunique()}')
print(f'children: {df.children.nunique()}')
print(f'sex: {df.sex.nunique()}')
print(f'smoker: {df.smoker.nunique()}')
print(f'region: {df.region.nunique()}')

UNIQUE:
age: 47
bmi: 548
children: 6
sex: 2
smoker: 2
region: 4

In [17]:
print("dtype: ")
print(f'age: {df.age.dtype}')
print(f'bmi: {df.bmi.dtype}')
print(f'children: {df.children.dtype}')
print(f'sex: {df.sex.dtype}')
print(f'smoker: {df.smoker.dtype}')
print(f'region: {df.region.dtype}')

dtype:
age: int64
bmi: float64
children: int64
sex: object
smoker: object
region: object

In [19]:
print("dtype: ")
print(f'age: {pd.api.types.is_numeric_dtype(df.age)}')
print(f'bmi: {pd.api.types.is_numeric_dtype(df.bmi)}')
print(f'children: {pd.api.types.is_numeric_dtype(df.children)}')
print(f'sex: {pd.api.types.is_numeric_dtype(df.sex)}')
print(f'smoker: {pd.api.types.is_numeric_dtype(df.smoker)}')
print(f'region: {pd.api.types.is_numeric_dtype(df.region)}')

dtype:
age: True
bmi: True
children: True
sex: False
smoker: False
region: False

In [ ]:
df.charges.std() # SD of sample

12110.011236693996

In [22]:
import numpy as np

In [ ]:
np.std(df.charges) # SD of Population

12105.484975561605

In [25]:
np.std(df.charges,ddof=1) # SD of Sample

12110.011236693996

In [33]:
from scipy.stats import kurtosis, skew
print(skew(df.charges,bias = False))
print(kurtosis(df.charges,bias = False))

1.5158796580240383
1.6062986532967916

In [34]:
print(df.charges.skew())
print(df.charges.kurtosis())

1.5158796580240388
1.6062986532967907